language: 
    - node_js
    
# whitelist
branches:
  only:
    - master

before_install: npm install -g grunt-cli
install: npm install

before_script:
    - sh -e /etc/init.d/xvfb start
    - git submodule update --init
    - cd addon-sdk
    - . bin/activate
    - cd ../addon

env:
    - DISPLAY=':99.0'

script: 
    - grunt
    - cfx test --verbose
